# Model close to simple resnet34 from experiment 12
# The only difference is in preactivation and expand -> stride argument
# for some reason this model has 17.25M params while simple resnet34 has 16.79M
# I'm too lazy to inspect it through netron. let's just hope it works

name : exp37.SimpR34_new
arch : BNet
model_params:
    stage_fns: ["simpl", "simpl", "simpl", "simpl"]
    block_fns: ["Pre_XX", "Pre_XX", "Pre_Btl", "Pre_Btl"]
    stage_args: [
        {"dim_reduction": "expand -> stride", "bottle_ratio": 1},
        {"dim_reduction": "expand -> stride", "bottle_ratio": 1},
        {"bottle_ratio": 1},
        {"bottle_ratio": 1},
    ]
    stem_width: 64
    head_width: 2048
    norm_act: leaky_relu
    stem_type: s2d
    layers: [3, 4, 6, 3]
    channels: [64, 128, 256, 512]
    mobilenetv3_head: False


weight_decay : 3e-5
smooth: true

ctwist: true
# very short period of ~3 epoch for ema: 0.9993 ** (2500 * 3) ~= 5e-3
ema_decay: 0.9993

# lr should be BS/256 * 0.1
phases : [
    {"ep": 0, "sz": 224, "bs": 256},
    {"ep": [0, 8], "lr": [0, 0.2], "mom": 0.9},
    {"ep": [8, 90], "lr": [0.2, 0], "mom": 0.9, "mode": "cos"},
]