# Model inspired by GNet
# Block 3 & 4 changes to Separable conv (with norm between DW and PW)
# should be compared to exp33 & 34 & 39
# the difference from 34 is in activation and dim_reduction in first blocks
# difference from 39: last stage 5 x 640 -> 1 x 1024. pre last stage 6 x 640 -> 10 x 480


name : exp40.GENet_preact_sep2_s2d_smaller_head
arch : BNet
model_params:
    stage_fns: ["simpl", "simpl", "simpl", "simpl"]
    block_fns: ["Pre_XX", "Pre_XX", "Pre_Sep2", "Pre_Sep2"]
    stage_args: [
        {"dim_reduction": "s2d", "bottle_ratio": 1},
        {"dim_reduction": "s2d", "bottle_ratio": 1},
        {"bottle_ratio": 1},
        {"bottle_ratio": 1},
    ]
    stem_width: 32
    head_width: 2560
    norm_act: leaky_relu
    stem_type: default
    layers: [1, 2, 10, 1]
    channels: [128, 192, 480, 1024]
    mobilenetv3_head: False


weight_decay : 3e-5
smooth: true

ctwist: true
# very short period of ~3 epoch for ema: 0.9993 ** (2500 * 3) ~= 5e-3
ema_decay: 0.9993

# lr should be BS/256 * 0.1
phases : [
    {"ep": 0, "sz": 224, "bs": 256},
    {"ep": [0, 8], "lr": [0, 0.2], "mom": 0.9},
    {"ep": [8, 90], "lr": [0.2, 0], "mom": 0.9, "mode": "cos"},
]