# +FixMatch
# Requires starting from sigmoid pretrained network 

name : exp81.BNet_small_fixmatch
arch : BNet
model_params:
    stage_fns: ["simpl", "simpl", "simpl", "simpl"]
    block_fns: ["Pre_XX", "Pre_XX", "Pre_Custom_2", "Pre_Custom_2"]
    stage_args: [
        {"dim_reduction": "stride & expand", "bottle_ratio": 1, "force_residual": True},
        {"dim_reduction": "stride & expand", "bottle_ratio": 1, "force_residual": True},
        {"bottle_ratio": 1, "dw_str2_kernel_size": 9, "filter_steps": 32},
        {"bottle_ratio": 1, "dw_str2_kernel_size": 9, "filter_steps": 128},
    ]
    stem_width: 32
    head_width: 2560
    norm_act: leaky_relu
    stem_type: s2d
    layers: [2, 4, 8, 2]
    channels: [64, 128, 256, 512]
    head_type: default


weight_decay : 3e-5
smooth: true
criterion: fixmatch
criterion_params:
    hard_weight: 0.5
fixmatch: true
resume: logs/exp77.BNet_small_kld_HNM_nov_20201018_113425/model.chpn
cutmix: 1.0
random_interpolation: false
rect_validation: false
resize_method: cubic
ctwist: true
# very short period of ~3 epoch for ema: 0.9993 ** (2500 * 3) ~= 5e-3
ema_decay: 0.9993

# lr should be BS/256 * 0.1
phases : [
    {"ep": 0, "sz": 224, "bs": 256},
    {"ep": [0, 8], "lr": [0, 0.2], "mom": 0.9},
    {"ep": [8, 90], "lr": [0.2, 0], "mom": 0.9, "mode": "cos"},
]
