# BResNet stands for Bonlime ResNet - unpublished variant of ResNet with all possible improvements and hacks
# This is an attemt to train ultimate encoder with low memory consumption (InplaceABN) and high accuracy
# Acc@1 80.182 Acc@5 94.992 in ~60h with some restarts. Need to run again later with drop_connect
# Acc@1 81.420 Acc@5 95.654 with full crop and larger image for validation

name : bresnet50_encoder_finetune
arch : resnet50
model_params : 
  stem_type: space2depth
  antialias: true
  attn_type: eca
  norm_layer: inplaceabn
  norm_act: leaky_relu
  drop_rate: 0.2
  drop_connect_rate: 0.2

weight_decay : 3e-5
cutmix : 1.0
smooth: True
ctwist : True
crop_method: full
resize_method: cubic
ema_decay: 0.9999 # using EMA instead of Lookahead
weight_standardization: True
# base lr should be 0.5625 = 0.75 * 192 / 256
# but want to train with lower LR because we train longer
phases : [
  {"ep": 0, "sz": 224, "val_sz": 288, "bs": 256},
  {"ep": [0, 8], "lr": [0, 0.2], "mom": 0.9}
  {"ep": [8, 200], "lr": [0.2, 0], "mode": "cos"}
#  {"ep": [0, 10], "lr": [0.003, 0], "mode": "cos", "mom": 0.9},
#  {"ep": [2, 100], "lr": [0.02, 0], "mode": "cos"},
]
