name : exp14.simpl_R34_noact_s2d_gr_w_16
arch : simpl_resnet34
model_params:
  stem_type: s2d
  groups_width: 16

weight_decay : 3e-5
smooth: true

ctwist: true
ema_decay: 0.9993

phases : [
    {"ep": 0, "sz": 224, "bs": 256},
    {"ep": [0, 8], "lr": [0, 0.2], "mom": 0.9},
    {"ep": [8, 90], "lr": [0.2, 0], "mom": 0.9, "mode": "cos"},
]