# R34 with removed residual in stride 2 blocks and additional conv in the head to remove
# representational bottleneck
# and no last activation in each block
# and space to depth input stem
name : exp12.simpl_R34_noact_s2d
arch : simpl_resnet34
model_params:
  stem_type: s2d
weight_decay : 3e-5
smooth: true

ctwist: true
# very short period of ~3 epoch for ema: 0.9993 ** (2500 * 3) ~= 5e-3
ema_decay: 0.9993

# lr should be BS/256 * 0.1
phases : [
    {"ep": 0, "sz": 224, "bs": 256},
    {"ep": [0, 8], "lr": [0, 0.2], "mom": 0.9},
    {"ep": [8, 90], "lr": [0.2, 0], "mom": 0.9, "mode": "cos"},
]


# Epoch 89/90. training: 2504it [24:54,  1.68it/s, Acc@1=78.476, Acc@5=92.434, Loss=1.9045]                                                                                                                    
# Epoch 89/90. validating: 101it [00:16,  6.12it/s, Acc@1=79.208, Acc@5=94.548, Loss=1.7978]                                                                                                                   
# [08-11 01:18:26] - Train loss: 1.9039 | Acc@1: 78.4616 | Acc@5: 92.4578                                                                                                                                      
# [08-11 01:18:26] - Val   loss: 1.9552 | Acc@1: 75.4920 | Acc@5: 92.4840                                                                                                                                      
# [08-11 01:18:26] - Epoch 89: best loss improved from 1.9554 to 1.9552                                                                                                                                        
# [08-11 01:18:26] - Epoch 90 | lr 1.65e-04                                                                                                                                                                    
# Epoch 90/90. training: 2504it [24:53,  1.68it/s, Acc@1=78.474, Acc@5=92.445, Loss=1.9037]
# Epoch 90/90. validating: 101it [00:16,  6.31it/s, Acc@1=71.796, Acc@5=90.432, Loss=2.1124]
# [08-11 01:43:54] - Train loss: 1.9035 | Acc@1: 78.4825 | Acc@5: 92.4667
# [08-11 01:43:54] - Val   loss: 1.9551 | Acc@1: 75.5240 | Acc@5: 92.4880
# [08-11 01:43:54] - Epoch 90: best loss improved from 1.9552 to 1.9551
# [08-11 01:43:55] - Acc@1 75.524 Acc@5 92.488
# [08-11 01:43:55] - Total time: 18h 28.6m 
