# GENet normal model with my training setup
# to run this experiment you need to git clone GENet to local directory (/home/zakirov/repoz in my case) 
# and run with the command below. you may also need to modify the train.py to process such argument
# because I'll remove the stab for this model after training is complete

# docker run --rm -it --shm-size 8G --gpus '"device=2,3"' \
#   -v $IMAGENET_DIR:/workdir/data/ \
#   -v `pwd`/logs/:/workdir/logs \
#   -v `pwd`/configs/:/workdir/configs \
#   -v /home/zakirov/repoz/GPU-Efficient-Networks/:/mnt/GPU-Efficient-Networks \
#   bonlime/imagenet:latest \
#  python3 -m torch.distributed.launch --nproc_per_node=2 \
#  train.py -c configs/exp27.GENet_normal.yaml


name : exp26.GENet_normal
arch : GENet_normal

weight_decay : 3e-5
smooth: true

ctwist: true
# very short period of ~3 epoch for ema: 0.9993 ** (2500 * 3) ~= 5e-3
ema_decay: 0.9993

# lr should be BS/256 * 0.1
phases : [
    {"ep": 0, "sz": 224, "bs": 256},
    {"ep": [0, 8], "lr": [0, 0.2], "mom": 0.9},
    {"ep": [8, 90], "lr": [0.2, 0], "mom": 0.9, "mode": "cos"},
]