# R34 with removed residual in stride 2 blocks and additional conv in the head to remove
# representational bottleneck
# and no last activation in each block
# and space to depth input stem
# and less classes
# very close to exp 12 but with no expand before head
# it means in experiment 22 it was 512 -> 2048 -> 100 classes and now it's just 512 -> 100 classes
# i'm expecting this config to have performance very close to 22
name : exp23.simpl_R34_noact_s2d
arch : simpl_resnet34
model_params:
  stem_type: s2d
  expand_before_head: False
weight_decay : 3e-5
smooth: true

ctwist: true
# very short period of ~3 epoch for ema: 0.9993 ** (2500 * 3) ~= 5e-3
ema_decay: 0.9993

# lr should be BS/256 * 0.1
phases : [
    {"ep": 0, "sz": 224, "bs": 256},
    {"ep": [0, 8], "lr": [0, 0.2], "mom": 0.9},
    {"ep": [8, 90], "lr": [0.2, 0], "mom": 0.9, "mode": "cos"},
]

classes_divisor: 10 # train on 100 classes instead

# Epoch 89/90. training: 2504it [10:56,  3.81it/s, Acc@1=75.967, Acc@5=91.574, Loss=1.8694]
# Epoch 89/90. validating: 101it [00:19,  5.23it/s, Acc@1=83.352, Acc@5=96.196, Loss=1.6013]
# [09-01 12:25:38] - Train loss: 1.8691 | Acc@1: 75.9689 | Acc@5: 91.5816
# [09-01 12:25:38] - Val   loss: 1.8580 | Acc@1: 76.5840 | Acc@5: 92.8160
# [09-01 12:25:38] - Epoch 89: best loss improved from 1.8582 to 1.8580
# [09-01 12:25:38] - Epoch 90 | lr 1.65e-04
# Epoch 90/90. training: 2504it [11:05,  3.76it/s, Acc@1=75.987, Acc@5=91.548, Loss=1.8684]
# Epoch 90/90. validating: 101it [00:18,  5.60it/s, Acc@1=69.792, Acc@5=89.424, Loss=2.1146]
# [09-01 12:37:02] - Train loss: 1.8684 | Acc@1: 75.9944 | Acc@5: 91.5674
# [09-01 12:37:02] - Val   loss: 1.8579 | Acc@1: 76.5400 | Acc@5: 92.8040
# [09-01 12:37:02] - Epoch 90: best loss improved from 1.8580 to 1.8579
# [09-01 12:37:03] - Acc@1 76.540 Acc@5 92.804
# [09-01 12:37:03] - Total time: 17h 5.8m