# R34 with removed residual in stride 2 blocks and additional conv in the head to remove
# representational bottleneck
# and no last activation in each block
# and space to depth input stem
# and less classes
# very close to exp 12
name : exp22.simpl_R34_noact_s2d
arch : simpl_resnet34
model_params:
  stem_type: s2d
weight_decay : 3e-5
smooth: true

ctwist: true
# very short period of ~3 epoch for ema: 0.9993 ** (2500 * 3) ~= 5e-3
ema_decay: 0.9993

# lr should be BS/256 * 0.1
phases : [
    {"ep": 0, "sz": 224, "bs": 256},
    {"ep": [0, 8], "lr": [0, 0.2], "mom": 0.9},
    {"ep": [8, 90], "lr": [0.2, 0], "mom": 0.9, "mode": "cos"},
]

classes_divisor: 10 # train on 100 classes instead

# Epoch 89/90. training: 2504it [10:56,  3.81it/s, Acc@1=77.936, Acc@5=92.606, Loss=1.7941]
# Epoch 89/90. validating: 101it [00:19,  5.21it/s, Acc@1=83.888, Acc@5=96.256, Loss=1.5667]
# [09-01 12:23:20] - Train loss: 1.7934 | Acc@1: 77.9517 | Acc@5: 92.6183
# [09-01 12:23:20] - Val   loss: 1.8106 | Acc@1: 77.2940 | Acc@5: 93.2340
# [09-01 12:23:20] - Epoch 89: best loss improved from 1.8107 to 1.8106
# [09-01 12:23:20] - Epoch 90 | lr 1.65e-04
# Epoch 90/90. training: 2504it [11:01,  3.78it/s, Acc@1=77.924, Acc@5=92.670, Loss=1.7922]
# Epoch 90/90. validating: 101it [00:19,  5.17it/s, Acc@1=70.700, Acc@5=90.192, Loss=2.0543]
# [09-01 12:34:42] - Train loss: 1.7924 | Acc@1: 77.9595 | Acc@5: 92.6587
# [09-01 12:34:42] - Val   loss: 1.8105 | Acc@1: 77.2980 | Acc@5: 93.2300
# [09-01 12:34:42] - Epoch 90: best loss improved from 1.8106 to 1.8105
# [09-01 12:34:43] - Acc@1 77.298 Acc@5 93.230
# [09-01 12:34:43] - Total time: 17h 7.1m