# Model inspired by GNet
# Block 3 & 4 changes to Separable conv (with norm between DW and PW)
# change number of filters and layers to be closer to RegNet and I personally think it should work better
# in this config I do expand first and only then conv with stride=2 in first blocks. It's ~10% slower. hope it would
# increase accuracy
# should be compared to exp35

name : exp36.GENet_preact_sep2_leaky_diff_stages_exp-str
arch : BNet
model_params:
    stage_fns: ["simpl", "simpl", "simpl", "simpl"]
    block_fns: ["Pre_XX", "Pre_XX", "Pre_Sep2", "Pre_Sep2"]
    stage_args: [
        {"dim_reduction": "expand -> stride", "bottle_ratio": 1},
        {"dim_reduction": "expand -> stride", "bottle_ratio": 1},
        {"bottle_ratio": 1},
        {"bottle_ratio": 1},
    ]
    stem_width: 32
    head_width: 2560
    norm_act: leaky_relu
    stem_type: s2d
    layers: [2, 4, 8, 2]
    channels: [64, 160, 416, 1024]
    mobilenetv3_head: False


weight_decay : 3e-5
smooth: true

ctwist: true
# very short period of ~3 epoch for ema: 0.9993 ** (2500 * 3) ~= 5e-3
ema_decay: 0.9993

# lr should be BS/256 * 0.1
phases : [
    {"ep": 0, "sz": 224, "bs": 256},
    {"ep": [0, 8], "lr": [0, 0.2], "mom": 0.9},
    {"ep": [8, 90], "lr": [0.2, 0], "mom": 0.9, "mode": "cos"},
]