# Model not linked to previous experiments
# Trying something that should work in my opinion
# this model is small (5.8M params) so I expect the performance to be lower

name : exp43.BNet_custom
arch : BNet
model_params:
    stage_fns: ["simpl", "simpl", "simpl", "simpl"]
    block_fns: ["Pre_XX", "Pre_XX", "Pre_Btl", "Pre_Btl"]
    stage_args: [
        {"dim_reduction": "expand -> stride", "bottle_ratio": 1, "force_residual": True},
        {"dim_reduction": "expand -> stride", "bottle_ratio": 1, "force_residual": True},
        {"bottle_ratio": 1, "force_residual": True, "groups_width": 1},
        {"bottle_ratio": 1, "force_residual": True, "groups_width": 1},
    ]
    stem_width: 32
    head_width: 2048
    norm_act: leaky_relu
    stem_type: s2d
    layers: [2, 4, 10, 2]
    channels: [64, 128, 192, 480]
    mobilenetv3_head: False


weight_decay : 3e-5
smooth: true

ctwist: true
# very short period of ~3 epoch for ema: 0.9993 ** (2500 * 3) ~= 5e-3
ema_decay: 0.9993

# lr should be BS/256 * 0.1
phases : [
    {"ep": 0, "sz": 224, "bs": 256},
    {"ep": [0, 8], "lr": [0, 0.2], "mom": 0.9},
    {"ep": [8, 90], "lr": [0.2, 0], "mom": 0.9, "mode": "cos"},
]