# close to exp52 & 53
# but with 3 layer MLP in head to compensate for small number of filters in the head
# 18.81M params


name : exp54.GEnet_wider_mlp3
arch : BNet
model_params:
    stage_fns: ["simpl", "simpl", "simpl", "simpl"]
    block_fns: ["Pre_XX", "Pre_XX", "Pre_IR", "Pre_IR"]
    stage_args: [
        {"dim_reduction": "stride & expand", "bottle_ratio": 1, "force_residual": True},
        {"dim_reduction": "stride & expand", "bottle_ratio": 1, "force_residual": True},
        {"bottle_ratio": 1, "force_residual": True, "dw_str2_kernel_size": 9, "force_expansion": True},
        {"bottle_ratio": 1, "force_residual": True, "dw_str2_kernel_size": 9, "force_expansion": True},
    ]
    stem_width: 32
    norm_act: leaky_relu
    stem_type: s2d
    layers: [1, 2, 6, 5]
    channels: [128, 192, 640, 640]
    mobilenetv3_head: False
    head_width: [1024, 1536, 2560]
    head_type: mlp_3
    head_norm_act: swish_hard

cutmix: 1.0
weight_decay : 3e-5
smooth: true

ctwist: true
# very short period of ~3 epoch for ema: 0.9993 ** (2500 * 3) ~= 5e-3
ema_decay: 0.9993

# lr should be BS/256 * 0.1
phases : [
    {"ep": 0, "sz": 224, "bs": 256},
    {"ep": [0, 8], "lr": [0, 0.2], "mom": 0.9},
    {"ep": [8, 90], "lr": [0.2, 0], "mom": 0.9, "mode": "cos"},
]