# close to exp48
# + MAE on cosine
# + Negative Contrastive loss
# resume: logs/exp90.BNet_asoft_ctmx_20201109_095536/model.chpn

name : exp96.BNet_d-softmax
arch : BNet
model_params:
    stage_fns: ["simpl", "simpl", "simpl", "simpl"]
    block_fns: ["Pre_XX", "Pre_XX", "Pre_IR", "Pre_IR"]
    stage_args: [
        {"dim_reduction": "stride & expand", "bottle_ratio": 1, "force_residual": True},
        {"dim_reduction": "stride & expand", "bottle_ratio": 1, "force_residual": True},
        {"bottle_ratio": 1, "force_residual": True, "dw_str2_kernel_size": 9, "force_expansion": True},
        {"bottle_ratio": 1, "force_residual": True, "dw_str2_kernel_size": 9, "force_expansion": True},
    ]
    stem_width: 32
    head_width: 64 # 256 # need much smaller for angular losses 2560
    norm_act: leaky_relu
    stem_type: s2d
    layers: [1, 2, 6, 5]
    channels: [128, 192, 640, 1024]
    head_type: default
    head_norm_act: none # only for exp87


criterion: my_loss_1
criterion_params:
    w_intra: 1 # 1
    w_inter: 1 # 1 # 0.1
#     intra_threshold: 0.98
    cos_intra: null
    
# cutmix: 1.0 # no cutmix for now
weight_decay : 3e-5
# smooth: true # not used in angular 
ctwist: true
blur: true
# very short period of ~3 epoch for ema: 0.9993 ** (2500 * 3) ~= 5e-3
ema_decay: 0.9993

# lr should be BS/256 * 0.1
phases : [
    {"ep": 0, "sz": 224, "bs": 256},
    {"ep": [0, 8], "lr": [0.01, 0.2], "mom": 0.9},
    {"ep": [8, 90], "lr": [0.2, 0], "mom": 0.9, "mode": "cos"},
]
