#### THIS IS A DRAFT OF CONFIG
# exp90 was successful but used fixed A-Softmax
# need to try 1. Cos Face (additive margin) 2. Cos Face + dynamic scale 

# close to exp48 and exp90
# + no last activation in head
# + smaller size of the head
# + angular margin (CosFace) loss with adaprive scale (AdaCos)

name : exp99.BNet_adacos_margin_res
arch : BNet
model_params:
    stage_fns: ["simpl", "simpl", "simpl", "simpl"]
    block_fns: ["Pre_XX", "Pre_XX", "Pre_IR", "Pre_IR"]
    stage_args: [
        {"dim_reduction": "stride & expand", "bottle_ratio": 1, "force_residual": True},
        {"dim_reduction": "stride & expand", "bottle_ratio": 1, "force_residual": True},
        {"bottle_ratio": 1, "force_residual": True, "dw_str2_kernel_size": 9, "force_expansion": True},
        {"bottle_ratio": 1, "force_residual": True, "dw_str2_kernel_size": 9, "force_expansion": True},
    ]
    stem_width: 32
    head_width: 128 # need much smaller for angular losses 2560
    norm_act: leaky_relu
    stem_type: s2d
    layers: [1, 2, 6, 5]
    channels: [128, 192, 640, 1024]
    # in exp.99 realized that we may need a better head! need to investigate this moment
    head_type: default
    head_norm_act: none # only for exp87

resume: logs/exp96.BNet_d-softmax_128_20201123_133305/model.chpn
# resume: logs/exp99.BNet_adacos_margin_20201225_092149/model.chpn
criterion: adacos
criterion_params:
    margin: 0.2
    
cutmix: 1.0
weight_decay : 3e-5
smooth: true
ctwist: true
blur: true
# very short period of ~3 epoch for ema: 0.9993 ** (2500 * 3) ~= 5e-3
ema_decay: 0.9993

# lr should be BS/256 * 0.1
phases : [
    {"ep": 0, "sz": 224, "bs": 256},
    {"ep": [0, 8], "lr": [0, 0.2], "mom": 0.9},
    {"ep": [8, 90], "lr": [0.2, 0], "mom": 0.9, "mode": "cos"},
]
