# config close to resnet34 but with more epochs
name : resnet34_long
arch : resnet34
model_params : {"deep_stem": true,"antialias": true}
weight_decay : 3e-5
cutmix : 1.0
ctwist : True
lookahead : True
phases : [
    {"ep": 0, "sz": 128, "bs": 256}, 
    {"ep": 120, "sz": 192, "bs": 256}, 
    {"ep": 240, "sz": 224, "bs": 256}, 
    {"ep": 360, "sz": 224, "bs": 256, "min_area": 0.2, "cutmix": 0.0, "ctwist": false},
    {"ep": [0, 10], "lr": [0, 0.5], "mom": 0.9},
    {"ep": [10, 360], "lr": [0.5, 0], "mode": "cos"},
    {"ep": [360, 400], "lr": [0.0001, 0.0001], "mode": "cos"},
]