# config close to one in Nvidia/DeepLearning examples.
# no smoothing due to sigmoid activation 
name : resnet50_baseline_sigm
arch : resnet50
weight_decay : 3e-5
sigmoid : True
phases : [
    {"ep": 0, "sz": 224, "bs": 256},
    {"ep": [0, 8], "lr": [0, 1.0], "mom": 0.9},
    {"ep": [8, 90], "lr": [1.0, 0], "mom": 0.9, "mode": "cos"},
]
