name : tresnetm
arch : tresnetm
weight_decay : 1e-4
cutmix : 1.0
ctwist : True
lookahead : True
phases : [
    {"ep": 0, "sz": 224, "bs": 256},
    {"ep": 300, "sz": 448, "bs": 64},
    {"ep": [0, 8], "lr": [0, 0.05], "mom": 0.9},
    {"ep": [8, 300], "lr": [0.05, 0], "mode": "cos"},
    {"ep": [300, 320], "lr": [0.001, 0], "mode": "cos"}, 
]
