# BResNet stands for Bonlime ResNet - unpublished variant of ResNet with all possible improvements and hacks
# This is an attemt to train ultimate encoder with Group Norm activatin and high accuracy
# Acc@1 80.732 Acc@5 95.623 with full crop and larger image for validation
# Resulta are worse than for usual BResNet. maybe because of dropout? maybe because of swish? who knows  
# 200 epochs are not enough. The loss is still decreasing even till the end and no sign of overfit
# Total time: 112h 39.5m (on 3xV100). 336 GPU hours wasted :(
name : bresnet50_encoder_agn
arch : resnet50
model_params : 
  stem_type: space2depth
  antialias: true
  attn_type: eca
  norm_layer: agn
  norm_act: swish
  drop_rate: 0.2
  drop_connect_rate: 0.2

weight_decay : 3e-5
cutmix : 1.0
smooth: True
ctwist : True
crop_method: full
resize_method: cubic
ema_decay: 0.9999 # using EMA instead of Lookahead
weight_standardization: True
# base lr should be 0.75 * 96 / 256
# but want to train with lower LR because we train longer
phases : [
  {"ep": 0, "sz": 224, "val_sz": 288, "bs": 96},
  {"ep": [0, 8], "lr": [0, 0.1], "mom": 0.9},
  {"ep": [8, 200], "lr": [0.1, 0], "mode": "cos"}
#   {"ep": [0, 10], "lr": [0.003, 0], "mode": "cos", "mom": 0.9},
#  {"ep": [2, 100], "lr": [0.02, 0], "mode": "cos"},
]
